### ISSUE TITLE
Full style guide

### ISSUE THREAD

**Issue by mghill** [place-labs/orthograph-err#8]
A lot of the current phase of customizing Orthograph-err is in finding & detailing specific exceptions. I foresee future stages involving higher/broader decisions such as consistent use of second person or title case, which are the typical jurisdiction of style guides. Textlint supports rule-presets which could be useful in both of these cases, or at least could be implemented alongside a full style guide as a fallback. 

For example, google has a style guide for technical documentation which has a community-implemented textlint-rule-preset
https://github.com/textlint-rule/textlint-rule-preset-google
and
https://developers.google.com/style

**Comment by kimburgess** [comment]
100% agree on setting up a rule preset, however it is a discussion outside the scope of orthograph-err.

As a tool, orthograph-err purely makes a [set of rules](https://github.com/place-labs/orthograph-err#supported-rules-engines) available. These are all disabled by default. When used as an action, it loads config from the repo's local `.textlintrc` which defines which rules should be enabled, and how they are configured. This configuration is then used to annotate the associated commits on GitHub.

I'll bump this issue across to our docs repo to continue discussion on how / where to create and publish a human read-able guide. That can then be used to create a textlint preset which encodes this, and can finally be loaded back here as the default behaviour.

**Comment by mghill** [comment]
Yep, that order of events makes sense to me. This is actually a docs issue which kinda surrounds orthograph-err.

**Comment by kimburgess** [comment]
GitHub does not appear to allow cross-org issue transfers. New issue created above to continue discussion.
